/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee.payroll;

/**
 *
 * @author ROG
 */

import java.sql.SQLException;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;



public class paySlippdf extends javax.swing.JFrame {

    /**
     * Creates new form paySlippdf
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    
    public paySlippdf() {
        initComponents();
        conn=DBConnection.java_DBConnection();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        txt_surname = new javax.swing.JTextField();
        txt_datehired = new javax.swing.JTextField();
        txt_jobtitle = new javax.swing.JTextField();
        txt_basicsalary = new javax.swing.JTextField();
        txt_medical = new javax.swing.JTextField();
        txt_tax = new javax.swing.JTextField();
        txt_ETF = new javax.swing.JTextField();
        txt_overtime = new javax.swing.JTextField();
        txt_bonus = new javax.swing.JTextField();
        txt_totalallowance = new javax.swing.JTextField();
        txt_loan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_EPF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_totaldeduction = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_netsalary = new javax.swing.JTextField();
        txt_other = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/searchbar.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 152, 44, 32));

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 152, 237, 32));

        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 260, 143, 25));

        jLabel3.setText("Surname");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 291, 143, 25));

        jLabel4.setText("Date Hired");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 322, 143, 25));

        jLabel5.setText("Job Title");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 353, 143, 25));

        jLabel6.setText("Basic Salary");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 384, 143, 25));

        jLabel7.setText("Medical ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 415, 143, 25));

        jLabel8.setText("Overtime");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 446, 143, 25));

        jLabel9.setText("Bonus");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 260, 143, 25));

        jLabel10.setText("Total Allowance");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 291, 143, 25));

        jLabel11.setText("Monthly Loan");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 322, 143, 25));

        jLabel12.setText("Tax");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 353, 143, 25));

        jLabel13.setText("ETF");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 384, 143, 25));

        txt_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_firstnameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 260, 151, 25));
        getContentPane().add(txt_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 291, 151, 25));

        txt_datehired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_datehiredActionPerformed(evt);
            }
        });
        getContentPane().add(txt_datehired, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 322, 151, 25));
        getContentPane().add(txt_jobtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 353, 151, 25));
        getContentPane().add(txt_basicsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 384, 151, 25));
        getContentPane().add(txt_medical, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 415, 151, 25));
        getContentPane().add(txt_tax, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 353, 151, 25));

        txt_ETF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ETFActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ETF, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 384, 151, 25));
        getContentPane().add(txt_overtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 446, 151, 25));
        getContentPane().add(txt_bonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 260, 151, 25));
        getContentPane().add(txt_totalallowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 291, 151, 25));

        txt_loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loanActionPerformed(evt);
            }
        });
        getContentPane().add(txt_loan, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 322, 151, 25));

        jLabel14.setText("EPF");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 415, 143, 25));
        getContentPane().add(txt_EPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 415, 151, 25));

        jLabel15.setText("Total Deduction");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 446, 143, 25));
        getContentPane().add(txt_totaldeduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 446, 151, 25));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("NET SALARY");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 572, 130, -1));

        txt_netsalary.setBackground(new java.awt.Color(204, 204, 255));
        txt_netsalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_netsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_netsalaryActionPerformed(evt);
            }
        });
        getContentPane().add(txt_netsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 569, 177, -1));
        getContentPane().add(txt_other, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 477, 151, 25));

        jLabel17.setText("Other");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 477, 143, 25));

        jButton1.setBackground(new java.awt.Color(102, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 662, 98, 32));

        jButton2.setBackground(new java.awt.Color(102, 0, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Genarate Slip");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 662, 150, 32));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(102, 0, 153));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Employee Payment Slip");

        jButton4.setBackground(new java.awt.Color(102, 0, 153));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/refresh.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        txtbill.setEditable(false);
        txtbill.setBackground(new java.awt.Color(229, 221, 221));
        txtbill.setColumns(20);
        txtbill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtbill.setRows(5);
        jScrollPane1.setViewportView(txtbill);

        jButton3.setBackground(new java.awt.Color(102, 0, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)))
                .addGap(65, 65, 65))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstnameActionPerformed

    private void txt_datehiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_datehiredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_datehiredActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
     // TODO add your handling code here:
     


        
    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_netsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_netsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_netsalaryActionPerformed

    private void txt_loanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loanActionPerformed

    private void txt_ETFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ETFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ETFActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        
        // search employee details bar
        

String empId = txt_search.getText();
try {
    // Fetch employee details
    String sql = "SELECT firstname, surname, datehired, jobtitle, basicsalary FROM staff_information WHERE id = ?";
    PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, empId);
    ResultSet rs = pst.executeQuery();

    if (rs.next()) {
        txt_firstname.setText(rs.getString("firstname"));
        txt_surname.setText(rs.getString("surname"));
        txt_datehired.setText(rs.getString("datehired"));
        txt_jobtitle.setText(rs.getString("jobtitle"));
        txt_basicsalary.setText(rs.getString("basicsalary"));
    } else {
        JOptionPane.showMessageDialog(null, "Employee not found in staff_information");
    }
    rs.close();
    pst.close();

    // Fetch allowances
    sql = "SELECT * FROM allowance WHERE id = ?";
    pst = conn.prepareStatement(sql);
    pst.setString(1, empId);
    rs = pst.executeQuery();

    if (rs.next()) {
        txt_medical.setText(rs.getString("medical"));
        txt_overtime.setText(rs.getString("overtime"));
        txt_other.setText(rs.getString("other"));
        txt_bonus.setText(rs.getString("bonus"));
        txt_totalallowance.setText(rs.getString("total_allowance"));
    } else {
        JOptionPane.showMessageDialog(null, "Allowances not found for employee");
    }
    rs.close();
    pst.close();

    // Fetch deductions
    sql = "SELECT loan, tax, ETF, EPF, totaldeduction FROM deduction WHERE id = ?";
    pst = conn.prepareStatement(sql);
    pst.setString(1, empId);
    rs = pst.executeQuery();

    if (rs.next()) {
        txt_loan.setText(rs.getString("loan"));
        txt_tax.setText(rs.getString("tax"));
        txt_ETF.setText(rs.getString("ETF"));
        txt_EPF.setText(rs.getString("EPF"));
        txt_totaldeduction.setText(rs.getString("totaldeduction"));
    } else {
        JOptionPane.showMessageDialog(null, "Deductions not found for employee");
    }
    rs.close();
    pst.close();

    // Calculate net salary
    try {
        double basicSalary = Double.parseDouble(txt_basicsalary.getText());
        double totalAllowance = Double.parseDouble(txt_totalallowance.getText());
        double totalDeduction = Double.parseDouble(txt_totaldeduction.getText());
        double netSalary = basicSalary + totalAllowance - totalDeduction;
        txt_netsalary.setText(String.valueOf(netSalary));
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Error calculating net salary: " + ex.getMessage());
    }

} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Database error: " + ex.getMessage());
}


        
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        // genarate employee payslip button
        

         txtbill.setText(txtbill.getText() + "------------------------------------------------------------------------------" + "\n");
         
         txtbill.setText(txtbill.getText() + "\t" +"  PAYMENT SLIP     " +"\n");
         
         
        txtbill.setText(txtbill.getText() + "------------------------------------------------------------------------------" + "\n\n\n");
        
        
        
        txtbill.setText(txtbill.getText() + "Employee Name:" + "  " + txt_firstname.getText() + "\n");

        txtbill.setText(txtbill.getText() + "Surname:" + "   " + txt_surname.getText() + "\n");

        txtbill.setText(txtbill.getText() + "Job Title:" + txt_jobtitle.getText() + "\n");
        
        txtbill.setText(txtbill.getText() + "Date Hired:" + txt_datehired.getText() + "\n");

        txtbill.setText(txtbill.getText() + "------------------------------------------------------------------------------" + "\n\n");

        txtbill.setText(txtbill.getText() + "Basic Salary:" + "\t" + "\t" + "\t" + txt_basicsalary.getText() + "\n");

        txtbill.setText(txtbill.getText() + "Allowance" + "\n");

        txtbill.setText(txtbill.getText() + "\t" + "Medical:" + "\t"  + txt_medical.getText() + "\n");

        txtbill.setText(txtbill.getText() + "\t" + "Overtime:" + "\t" + txt_overtime.getText() + "\n");

        txtbill.setText(txtbill.getText() + "\t" + "Other" + "\t"  + txt_other.getText() + "\n");
        
        txtbill.setText(txtbill.getText() + "Bonus" + "\t" + "\t" + txt_bonus.getText() + "\n");
        
        txtbill.setText(txtbill.getText() + "Total Allowance" + "\t" + "\t" + txt_totalallowance.getText() + "\n");
        
        txtbill.setText(txtbill.getText() + "------------------------------------------------------------------------------" + "\n");

        txtbill.setText(txtbill.getText() + "Deductions" + "\n");

        txtbill.setText(txtbill.getText() + "\t" + "Monthly Loan" + "\t" + txt_loan.getText() + "\n");

        txtbill.setText(txtbill.getText() + "\t" + "Tax" + "\t" + txt_tax.getText() + "\n");

        txtbill.setText(txtbill.getText() + "\t" + "ETF" + "\t" + txt_ETF.getText() + "\n");
        
        txtbill.setText(txtbill.getText() + "EPF" + "\t" + "\t" + txt_EPF.getText() + "\n");

        txtbill.setText(txtbill.getText() + "Total Deduction" + "\t" + "\t" + txt_totaldeduction.getText() + "\n");

        txtbill.setText(txtbill.getText() + "\t" + "\t" + "                        " + "------------------" + "\n");

        txtbill.setText(txtbill.getText() + "Net Salary" + "\t" + "\t" + "\t" + txt_netsalary.getText() + "\n");

        txtbill.setText(txtbill.getText() + "\t" + "\t" + "                       " + "------------------" + "\n");

        txtbill.setText(txtbill.getText() + "\t" + "\t" + "                       " + "------------------" + "\n" + "\n");

 
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // clear feild button
        
        
        txt_datehired.setText("");
        txt_firstname.setText("");
        txt_surname.setText("");
        txt_jobtitle.setText("");
        txt_basicsalary.setText("");
        txt_medical.setText("");
        txt_overtime.setText("");
        txt_other.setText("");
        txt_search.setText("");
        txt_bonus.setText("");
        txt_totalallowance.setText("");
        txt_loan.setText("");
        txt_tax.setText("");
        txt_ETF.setText("");
        txt_EPF.setText("");
        txt_totaldeduction.setText("");
        txt_netsalary.setText("");
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        // print employee payslip as a pdf button
        
     try{
     
     
       txtbill.print();
     
     
     }catch(Exception e){
     
     
     
     }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        MainMenu view  = new MainMenu();
        view.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
    
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paySlippdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paySlippdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paySlippdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paySlippdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paySlippdf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_EPF;
    private javax.swing.JTextField txt_ETF;
    private javax.swing.JTextField txt_basicsalary;
    private javax.swing.JTextField txt_bonus;
    private javax.swing.JTextField txt_datehired;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_jobtitle;
    private javax.swing.JTextField txt_loan;
    private javax.swing.JTextField txt_medical;
    private javax.swing.JTextField txt_netsalary;
    private javax.swing.JTextField txt_other;
    private javax.swing.JTextField txt_overtime;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_tax;
    private javax.swing.JTextField txt_totalallowance;
    private javax.swing.JTextField txt_totaldeduction;
    private javax.swing.JTextArea txtbill;
    // End of variables declaration//GEN-END:variables
}
